### ISSUE TITLE
Difference between ForecastTKGQA and BERT_ext

### ISSUE THREAD

**Issue by minjunp** [ZifengDing/ForecastTKGQA#1]
Hi, thank you for the great work! I have a question for the Table 5 (Experimental results over ForecastTKGQA) in the paper. What's the difference between BERT_ext and ForecastTKGQA? If I understood correctly, aren't both BERT_ext and ForecastTKGQA using TANGO representations of quadruple and transforms queries using BERT?

**Comment by ZifengDing** [comment]
Hi!

BERT_ext is using feed forward neural network for score computation. ForecastTKGQA uses the score function designed in Section 4.2. Please also refer to Appendix B.2 for details about BERT_ext implementation.

**Comment by minjunp** [comment]
Thank you!
