### ISSUE TITLE
No such file or directory: 'data/ICEWS21/kg/tkbc_processed_data/ICEWS21/ent_id'

### ISSUE THREAD

**Issue by Jin1c-3** [ZifengDing/ForecastTKGQA#2]
## Traceback:
(ForecastTKGQA) D:\Code\TKGQA\ForecastTKGQA\Code\ForecastTKGQA>python trainer.py --tkg_model_file tango_submission.pkl --model forecasttkgqa --lm_model distilbert --batch_size 256 --max_epochs 200 --valid_freq 1 --save_to forecasttkgqa --question_type fact_reasoning --device 0
Loading tango model from models/ICEWS21/kg_embeddings/tango_submission.pkl
D:\Code\TKGQA\ForecastTKGQA\Code\ForecastTKGQA\utils.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  time2emb[k] = torch.tensor(v[:20575], requires_grad=False, device='cpu')
tkg embed: 200
Model is forecasttkgqa
Traceback (most recent call last):
  File "trainer.py", line 330, in <module>
    main()
  File "trainer.py", line 240, in main
    train_dataloader, valid_dataloader, test_dataloader, valid_dataset, test_dataset = prepare_data(args)
  File "trainer.py", line 63, in prepare_data
    train_dataset = QADatasetForecast(split='train', dataset_name=args.dataset_name,
  File "D:\Code\TKGQA\ForecastTKGQA\Code\ForecastTKGQA\qa_datasets.py", line 395, in __init__
    super().__init__(split, dataset_name, question_type, tokenization_needed, pct)
  File "D:\Code\TKGQA\ForecastTKGQA\Code\ForecastTKGQA\qa_datasets.py", line 54, in __init__
    self.all_dicts = utils.getAllDicts(dataset_name)
  File "D:\Code\TKGQA\ForecastTKGQA\Code\ForecastTKGQA\utils.py", line 78, in getAllDicts
    in_file = open(str(base_path + f), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/ICEWS21/kg/tkbc_processed_data/ICEWS21/ent_id'

## Probable reason:
I found that `ent_id`, `rel_id`, and `ts_id` are missing. After I converted `wd_id2entity_text.txt`, `wd_id2relation_text.txt`, and `ts2id.txt` to pickle files, the code encountered a type error. This leads me to believe there may be **data loss**.

**Comment by ZifengDing** [comment]
Hi,

Thank you so much for pointing this out. I think I missed some files when I was uploading. Now I have updated the dropbox files. Could you please check it?

And if you meet other problems during reproducing experiments, please notice me. I will fix it asap.

**Comment by Jin1c-3** [comment]
Thank you so much, code works well!!
